services:
  postgres:
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${POSTGRES_MASTER_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_MASTER_PASS:?database password required}
      POSTGRES_USER: ${POSTGRES_MASTER_USER:-postgres}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
    - database:/var/lib/postgres/data
    - ./postgres/init.sh:/docker-entrypoint-initdb.d/01-init.sh

  authentik-server:
    command: server
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASS:?authentik postgres password required}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.2}
    ports:
    - 127.0.0.1:${COMPOSE_PORT_HTTP:-9000}:9000
    - 127.0.0.1:${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - ./authentik/data:/data
    - ./authentik/custom-templates:/templates

  authentik-worker:
    command: worker
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.2}
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./authentik/data:/data
    - ./certs:/certs
    - ./authentik/custom-templates:/templates

  squid-proxy:
    build: ./squid
    image: squid-local:alpine
    restart: unless-stopped
    ports:
      - "3128:3128"
    volumes:
      - ./squid/cache:/var/cache/squid
      - ./squid/logs:/var/log/squid
      - ./squid/etc:/etc/squid

volumes:
  database:
    driver: local
