#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    BEGIN TRANSACTION;

    CREATE USER ${AUTHENTIK_POSTGRES_USER} WITH PASSWORD '${AUTHENTIK_POSTGRES_PASS}';
    CREATE DATABASE ${AUTHENTIK_POSTGRES_DB} OWNER ${AUTHENTIK_POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${AUTHENTIK_POSTGRES_DB} TO ${AUTHENTIK_POSTGRES_USER};

    

    COMMIT;
EOSQL
